# Generated by Django 6.0.2 on 2026-03-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название лекции')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя (например, topic-1)')),
                ('image_url', models.CharField(default='/images/default.jpg', max_length=500, verbose_name='Путь к картинке')),
                ('related_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='education.test', verbose_name='Связанный тест')),
            ],
        ),
    ]
