# Generated by Django 6.0.3 on 2026-03-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='content',
            field=models.TextField(blank=True, help_text='Здесь будет текст лекции, формулы и теги картинок', verbose_name='Содержание лекции'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео (YouTube)'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image_url',
            field=models.CharField(default='/images/default.jpg', max_length=500, verbose_name='Путь к превью-картинке'),
        ),
    ]
